# Lab 2 - biblioteka NumPy

NumPy (https://numpy.org) to jedna z najpopularniejszych bibliotek języka Python
przeznaczona do obliczeń numerycznych na tensorach w formie tablic.

## Instalacja

W celu instalacji pakietu NumPy należy wpisać
w terminalu polecenie **pip install numpy**

## Import biblioteki

Bibliotekę NumPy, podobnie jak każdy inny zewnętrzny pakiet, należy zaimportować.
Służy do tego instrukcja import. Dobrą praktyką jest importowanie biblioteki NumPy z aliasem np,
co można zapisać następująco:

In [1]:
import numpy as np

## Tworzenie nowych tablic na podstawie list

Najprostszą metodą utworzenia tablicy NumPy jest przekazanie listy wartości do funkcji array z pakietu NumPy:

In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


W podobny sposób można tworzyć również tablice wielowymiarowe (tensory).
W tym celu należy przekazać do funkcji array z pakietu NumPy listę wielowymiarową.

In [9]:
arr_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
])

arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Typy danych w NumPy

Typy danych w bibliotece NumPy definiują charakter wartości przechowywanych w tablicach.
Typ może zostać ustalony automatycznie bądź wskazany manualnie (w celu optymalizacji pamięci) za pomocą parametru dtype.

In [10]:
arr_int = np.array([1, 2, 3, 4, 5], dtype='i')

arr_int

array([1, 2, 3, 4, 5], dtype=int32)

Typ wartości w tablicy można sprawdzić za pomocą atrybutu dtype.

In [11]:
arr_int.dtype


dtype('int32')

### Podstawowe typy danych w NumPy

Wyróżniany następujące podstawowe typy danych występujące w bibliotece NumPy

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type (void)

### Złożone typy danych w NumPy

W typie danych można również wskazać ilość zarezerwowanego miejsca na wartość.
Przykładowo, "i4" oznacza typ integer (całkowitoliczbowy) 4-bajtowy.

In [12]:
arr = np.array([1, 2, 3, 4, 5], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


## Tworzenie tablic przy użyciu funkcji numpy

Pakiet NumPy umożliwia również tworzenie tablic wypełnionych wartościami.

Funkcja zeros służy do tworzenia tablic o wskazanym rozmiarze, wypełnionych zerami:

In [15]:
np.zeros(10, dtype='i')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

Funkcji zeros można również użyć do tworzenia tablic wielowymiarowych:

In [16]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Bardzo podobne zastosowanie ma funkcja ones, która tworzy tablice wypełnione jedynkami:

In [17]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Do stworzenia przestrzeni liniowej o wskazanym zakresie i liczbie elementów należy użyć funkcji linspace

In [18]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

Funkcja eye utworzy macierz jednostkową (kwadratową) o wskazanym rozmiarze:

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Za pomocą funkcji rand pochodzącej z modułu random w pakiecie NumPy
można wygenerować tensor o wskazanym rozmiarze zawierający wartości losowe
pochodzące z rozkładu normalnego jednorodnego, w przedziale [0-1):

In [21]:
np.random.rand(5)


array([0.44063842, 0.31148889, 0.46739548, 0.81764391, 0.51210235])

In [22]:
np.random.rand(3, 2)

array([[0.23019164, 0.89028114],
       [0.26463188, 0.96178653],
       [0.53000117, 0.44314588]])

Funkcja randn pochodząca z modułu random w pakiecie NumPy ma podobne zastosowanie do funkcji rand.
Różnica między nimi polega na generowaniu wartości losowych pochodzących z rozkładu normalnego:

In [23]:
np.random.randn(5, 5)


array([[ 2.47086539,  2.96293713,  2.58018966, -0.92043582, -0.81360505],
       [-0.8752674 , -0.33152786, -1.65257936, -1.58292523,  0.35601633],
       [ 1.53245974,  0.6055035 ,  0.74449238, -1.48569168, -0.59746734],
       [ 0.46908226, -0.49933416, -0.75823683,  0.12113281,  0.88909965],
       [ 0.85535491, -0.6933199 , -1.00784151,  1.85445843,  0.226977  ]])

Funkcja randint pochodząca z modułu random w pakiecie NumPy ma również podobne zastosowanie do swoich poprzedniczek.
Różnica polega na generowaniu wartości losowych z wyznaczonych przedziałów:

In [24]:
np.random.randint(1, 49, (3, 6))

array([[11, 48, 20,  6, 21,  8],
       [ 4, 36, 22, 24, 27, 18],
       [ 7, 39, 38, 43, 27, 42]])

## Indeksowanie danych w tablicach

Biblioteka NumPy umożliwia wygodne wybieranie wartości znajdujących się w tablicach za pomocą wskazania ich pozycji.

In [26]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Wiersz z takiej tablicy można pobrać wskazując jego indeks:

In [27]:
arr_2d[0]

array([ 5, 10, 15])

Wartośc skalarną można pobrać wskazując jej konkretną pozycję w formacie [wiersz, kolumna]:

In [28]:
arr_2d[1, 2]


30

Kolumnę z tablicy można pobrać wskazując wszystkie wiersze za pomocą znaku : oraz indeks kolumny w następującym formacie [:, col]:

In [29]:
arr_2d[:, 1]

array([10, 25, 40])

Za pomocą indeksu -1 można pobrać ostatnią wartość we wskazanym wymiarze:

In [30]:
arr_2d[-1, -1]

45

Biblioteka NumPy umożliwia również pobieranie podtablic za pomocą zakresów indeksów wskazanych w konkretnych wymiarach:

In [31]:
matrix = np.random.randint(1, 100, (5, 5))

matrix

array([[25, 32, 53, 90,  7],
       [37, 68,  9, 11, 30],
       [41, 38,  5, 78, 74],
       [34, 27, 85, 30, 80],
       [45, 38, 80, 33, 12]])

In [32]:
matrix[1:4, 1:4]

array([[68,  9, 11],
       [38,  5, 78],
       [27, 85, 30]])

## Kształt tablicy i jego modyfikacja

Kształt tablicy można sprawdzić za pomocą atrybutu shape:

In [34]:
arr = np.ones((5, 4))

print(arr)

arr.shape

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


(5, 4)

Wynik (5, 4) informuje nas o 5 wierszach i 4 kolumnach macierzy.

Za pomocą funkcji reshape można zmodyfikować kształt tablicy.

In [36]:
arr = np.ones(25)

arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
arr.reshape((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Wyszukiwanie w tablicach wartości największych i najmniejszych

In [42]:
arr = np.random.randint(1, 100, 10)

arr

array([72, 40,  8, 50, 40, 39, 64, 50,  3, 50])

Za pomocą metody min można znaleźć wartość największą:

In [43]:
arr.min()


3

Wartość największą można znaleźć za pomocą metody max:

In [44]:
arr.max()

72

Pozycję elementu o największej lub najmniejszej wartości można znaleźć za pomocą metod argmax i argmin:

In [46]:
print(f'wartosc najwieksza: {arr.max()}, pozycja wartosci najwiekszej: {arr.argmax()}')
print(f'wartosc najmniejsza: {arr.min()}, pozycja wartosci najmniejszej: {arr.argmin()}')

wartosc najwieksza: 72, pozycja wartosci najwiekszej: 0
wartosc najmniejsza: 3, pozycja wartosci najmniejszej: 8


## Funkcje matematyczny w NumPy

Pakiet NumPy dostarcza wiele funkcji matematycznych dokonujących operacji na wszystkich elementach tablic.

In [47]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Za pomocą funkcji sqrt można obliczyć pierwiastki kwadratowe wszystkich elementów znajdujących się w tablicy:

In [48]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

Za pomocą funkcji exp można wyznaczyć wartość wyrażenia $$e ^ x$$ gdzie x to każdy kolejny element znajdujący się w tablicy:

In [49]:
np.exp(arr)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

## Arytmetyka i algebra tablic

Pakiet NumPy umożliwia również wygodne dokonywanie działań arytmetycznych oraz algebraicznych na tablicach:

In [50]:
arr0 = np.random.randint(1, 10, (3, 3))
arr1 = np.random.randint(1, 10, (3, 3))

arr0, arr1

(array([[6, 4, 6],
        [6, 2, 3],
        [8, 2, 8]]),
 array([[2, 7, 7],
        [6, 5, 7],
        [1, 2, 8]]))

Działań arytmetycznych na tablicach można dokonać za pomocą klasycznych operatorów arytmetycznych:

In [51]:
arr0 + arr1

array([[ 8, 11, 13],
       [12,  7, 10],
       [ 9,  4, 16]])

In [52]:
arr0 - arr1

array([[ 4, -3, -1],
       [ 0, -3, -4],
       [ 7,  0,  0]])

In [53]:
arr0 * arr1

array([[12, 28, 42],
       [36, 10, 21],
       [ 8,  4, 64]])

In [54]:
arr0 ** 2

array([[36, 16, 36],
       [36,  4,  9],
       [64,  4, 64]])

Pakiet NumPy udostępnia również interfejs do dokonywania operacji algebraicznych na tensorach.

Do wyznaczenia iloczynu skalarnego dwóch tensorów służy metoda dot:

In [55]:
arr0.dot(arr1)


array([[ 42,  74, 118],
       [ 27,  58,  80],
       [ 36,  82, 134]])

In [57]:
arr0[0].dot(arr1[1])


98

## Zadania

1. Utworzyć tablicę zawierającą 50 piątek
2. Utworzyć tablicę o rozmiarze 5x5 z wartościami od 1 do 25
3. Utworzyć tablicę tablicę liczb parzystych od 10 do 50
4. Utworzyć macierz, w której na przekątnej znajdą się wartości równe 8, a pozostałe będą wynosiły 0
5. Utworzyć tablicę o rozmiarze 10x10 z wartościami zwiększającymi się o 0.01
6. Utworzyć przestrzeń liniową 50 wartości z zakresu 0-1
7. Wybrać podtablicę 12-elementową, z tablicy utworzonej w zadaniu 2, z wartościami w zakresie 12-15
8. Wybrać 3 pierwsze elementy z ostatniej kolumny tablicy utworzonej w zadaniu 2, a następnie ułożyć z nich kolumnę
9. Wyznaczyć sumę wartości elementów znajdujących się w dwóch ostatnich wierszach macierzy utworzonej w zadaniu 2
10. Przygotować skrypt, który stworzy tensor zawierający losowe wartości całkowite, losowym wymiarze i losowym rozmiarze każdego z wymiarów